unit uSplashConstants;

interface

const
  EPOS_MANAGER_SPLASH_SCREEN       = 'EPOS_MANAGER_SPLASH_IMAGE';
  SERVICE_WATCHDOG_SPLASH_SCREEN   = 'SERVICE_WATCHDOG_SPLASH_IMAGE';
  ESTATE_MANAGEMENT_SPLASH_SCREEN  = 'ESTATE_MANAGEMENT_SPLASH_IMAGE';
  VSS_BUILD_TOOL_SPLASH_SCREEN     = 'VSS_BUILD_TOOL_SPLASH_IMAGE';
  AZTEC_RELEASENOTES_SPLASH_SCREEN = 'AZTEC_RELEASENOTES_SPLASH_IMAGE';
  SHELF_EDGE_LABELS_SPLASH_SCREEN  = 'SHELF_EDGE_LABELS_SPLASH_IMAGE';
  XML_PRODUCT_IMPORT_SPLASH_SCREEN = 'XML_PRODUCT_IMPORT_SPLASH_IMAGE';
  RELEASE_MANAGER_SPLASH_SCREEN    = 'RELEASE_MANAGER_SPLASH_IMAGE';

implementation

end.
