unit RpcConstants;

interface

// these values are used by CoInitializeSecurity
const
  {$EXTERNALSYM RPC_C_AUTHN_LEVEL_DEFAULT}
  RPC_C_AUTHN_LEVEL_DEFAULT       = 0;
  {$EXTERNALSYM RPC_C_AUTHN_LEVEL_NONE}
  RPC_C_AUTHN_LEVEL_NONE          = 1;
  {$EXTERNALSYM RPC_C_AUTHN_LEVEL_CONNECT}
  RPC_C_AUTHN_LEVEL_CONNECT       = 2;
  {$EXTERNALSYM RPC_C_AUTHN_LEVEL_CALL}
  RPC_C_AUTHN_LEVEL_CALL          = 3;
  {$EXTERNALSYM RPC_C_AUTHN_LEVEL_PKT}
  RPC_C_AUTHN_LEVEL_PKT           = 4;
  {$EXTERNALSYM RPC_C_AUTHN_LEVEL_PKT_INTEGRITY}
  RPC_C_AUTHN_LEVEL_PKT_INTEGRITY = 5;
  {$EXTERNALSYM RPC_C_AUTHN_LEVEL_PKT_PRIVACY}
  RPC_C_AUTHN_LEVEL_PKT_PRIVACY   = 6;

  {$EXTERNALSYM RPC_C_IMP_LEVEL_DEFAULT}
  RPC_C_IMP_LEVEL_DEFAULT      = 0;
  {$EXTERNALSYM RPC_C_IMP_LEVEL_ANONYMOUS}
  RPC_C_IMP_LEVEL_ANONYMOUS    = 1;
  {$EXTERNALSYM RPC_C_IMP_LEVEL_IDENTIFY}
  RPC_C_IMP_LEVEL_IDENTIFY     = 2;
  {$EXTERNALSYM RPC_C_IMP_LEVEL_IMPERSONATE}
  RPC_C_IMP_LEVEL_IMPERSONATE  = 3;
  {$EXTERNALSYM RPC_C_IMP_LEVEL_DELEGATE}
  RPC_C_IMP_LEVEL_DELEGATE     = 4;

  {$EXTERNALSYM RPC_C_AUTHN_NONE}
  RPC_C_AUTHN_NONE          = 0;
  {$EXTERNALSYM RPC_C_AUTHN_DCE_PRIVATE}
  RPC_C_AUTHN_DCE_PRIVATE   = 1;
  {$EXTERNALSYM RPC_C_AUTHN_DCE_PUBLIC}
  RPC_C_AUTHN_DCE_PUBLIC    = 2;
  {$EXTERNALSYM RPC_C_AUTHN_DEC_PUBLIC}
  RPC_C_AUTHN_DEC_PUBLIC    = 4;
  {$EXTERNALSYM RPC_C_AUTHN_GSS_NEGOTIATE}
  RPC_C_AUTHN_GSS_NEGOTIATE = 9;
  {$EXTERNALSYM RPC_C_AUTHN_WINNT}
  RPC_C_AUTHN_WINNT         = 10;
  {$EXTERNALSYM RPC_C_AUTHN_GSS_SCHANNEL}
  RPC_C_AUTHN_GSS_SCHANNEL  = 14;
  {$EXTERNALSYM RPC_C_AUTHN_GSS_KERBEROS}
  RPC_C_AUTHN_GSS_KERBEROS  = 16;
  {$EXTERNALSYM RPC_C_AUTHN_DPA}
  RPC_C_AUTHN_DPA           = 17;
  {$EXTERNALSYM RPC_C_AUTHN_MSN}
  RPC_C_AUTHN_MSN           = 18;
  {$EXTERNALSYM RPC_C_AUTHN_DIGEST}
  RPC_C_AUTHN_DIGEST        = 21;
  {$EXTERNALSYM RPC_C_AUTHN_MQ}
  RPC_C_AUTHN_MQ            = 100;
  {$EXTERNALSYM RPC_C_AUTHN_DEFAULT}
  RPC_C_AUTHN_DEFAULT       = $FFFFFFFF;

  {$EXTERNALSYM RPC_C_AUTHZ_NONE}
  RPC_C_AUTHZ_NONE    = 0;
  {$EXTERNALSYM RPC_C_AUTHZ_NAME}
  RPC_C_AUTHZ_NAME    = 1;
  {$EXTERNALSYM RPC_C_AUTHZ_DCE}
  RPC_C_AUTHZ_DCE     = 2;
  {$EXTERNALSYM RPC_C_AUTHZ_DEFAULT}
  RPC_C_AUTHZ_DEFAULT = $ffffffff;


  {$EXTERNALSYM EOAC_NONE}
  EOAC_NONE	          = 0;
  {$EXTERNALSYM EOAC_MUTUAL_AUTH}
  EOAC_MUTUAL_AUTH	  = $1;
  {$EXTERNALSYM EOAC_STATIC_CLOAKING}
  EOAC_STATIC_CLOAKING	  = $20;
  {$EXTERNALSYM EOAC_DYNAMIC_CLOAKING}
  EOAC_DYNAMIC_CLOAKING   = $40;
  {$EXTERNALSYM EOAC_ANY_AUTHORITY}
  EOAC_ANY_AUTHORITY	  = $80;
  {$EXTERNALSYM EOAC_MAKE_FULLSIC}
  EOAC_MAKE_FULLSIC	  = $100;
  {$EXTERNALSYM EOAC_DEFAULT}
  EOAC_DEFAULT	          = $800;
  {$EXTERNALSYM EOAC_SECURE_REFS}
  EOAC_SECURE_REFS	  = $2;
  {$EXTERNALSYM EOAC_ACCESS_CONTROL}
  EOAC_ACCESS_CONTROL	  =  $4;
  {$EXTERNALSYM EOAC_APPID}
  EOAC_APPID	          = $8;
  {$EXTERNALSYM EOAC_DYNAMIC}
  EOAC_DYNAMIC	          = $10;
  {$EXTERNALSYM EOAC_REQUIRE_FULLSIC}
  EOAC_REQUIRE_FULLSIC	  = $200;
  {$EXTERNALSYM EOAC_AUTO_IMPERSONATE}
  EOAC_AUTO_IMPERSONATE	  = $400;
  {$EXTERNALSYM EOAC_NO_CUSTOM_MARSHAL}
  EOAC_NO_CUSTOM_MARSHAL  = $2000;
  {$EXTERNALSYM EOAC_DISABLE_AAA}
  EOAC_DISABLE_AAA	  = $1000;

implementation

end.
